#Problem 29
#Distinct Powers
#
#If they are then placed in numerical order, with any repeats removed, we get the 
#following sequence of 15 distinct terms:
#How many distinct terms are in the sequence generated by a**b for 2<=a<=100 and  
#2<=b<=100 ?
c={i**f for i in range(2,101) for f in range(2,101)}
print(len(c))
